<?php

namespace AppBundle\Repository;

/**
 * AssociationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssociationsRepository extends \Doctrine\ORM\EntityRepository
{
}
