<?php

namespace AppBundle\Repository;

/**
 * ShowcaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShowcaseRepository extends \Doctrine\ORM\EntityRepository
{
}
