services:
    services.loadconfig:
        class: AppBundle\Services\LoadConfig
        arguments:
            - "@doctrine.orm.entity_manager"

    services.loaddashboard:
        class: AppBundle\Services\LoadDashboard
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%var_project%"

    app.sendEmail:
        class: AppBundle\Services\SendEmail
        arguments:
            - "@templating"
            - "@mailer"



